export interface MenuItem {
  id: string;
  category: "deli" | "hot" | "vegan" | "snacks" | "desserts" | "coffee";
  name: string;
  description?: string;
  price: number;
  currency: string;
  image?: string;
  nutrition?: {
    calories?: number;
    protein?: number; // grams
    carbs?: number; // grams
    fat?: number; // grams
    fiber?: number; // grams
  };
  tags?: string[]; // e.g., ["vegan", "gluten-free", "spicy"]
}

export const menuItems: MenuItem[] = [
  // ========== DELI SANDWICHES ==========
  {
    id: "deli-1",
    category: "deli",
    name: "Roast Beef",
    description: "Served with lettuce, tomatoes & topped with a choice of Healthy Mustard or Healthy Mayonnaise",
    price: 260,
    currency: "EGP",
    nutrition: { calories: 280, protein: 23.6, carbs: 6.4, fat: 24 },
    tags: ["high-protein", "low-carb"],
  },
  {
    id: "deli-2",
    category: "deli",
    name: "Smoked Turkey with Cheese",
    description: "Served with lettuce, tomatoes, slice of Cheddar cheese topped with Healthy Mayonnaise",
    price: 230,
    currency: "EGP",
    nutrition: { calories: 387, protein: 30, carbs: 6.7, fat: 32 },
    tags: ["high-protein"],
  },
  {
    id: "deli-3",
    category: "deli",
    name: "Smoked Chicken",
    description: "Served with lettuce & tomatoes, topped with Healthy Mayonnaise",
    price: 200,
    currency: "EGP",
    nutrition: { calories: 266, protein: 25, carbs: 7.4, fat: 23 },
    tags: ["high-protein", "low-carb"],
  },
  {
    id: "deli-4",
    category: "deli",
    name: "Smoked Salmon",
    description: "Served with Avocado slices, fresh greens, squeezed lime, topped with Healthy Mayonnaise",
    price: 350,
    currency: "EGP",
    nutrition: { calories: 346, protein: 20.1, carbs: 8, fat: 24.4 },
    tags: ["high-protein", "omega-3"],
  },
  {
    id: "deli-5",
    category: "deli",
    name: "Club Sandwich",
    description: "Layers of Toast filled with Smoked Turkey, Smoked chicken, lettuce, tomatoes & Cheddar Cheese",
    price: 330,
    currency: "EGP",
    nutrition: { calories: 521, protein: 42.6, carbs: 8.5, fat: 35.6 },
    tags: ["high-protein"],
  },
  {
    id: "deli-6",
    category: "deli",
    name: "Tuna",
    description: "Your choice of Toast or Fino Bread filled with tuna salad mixed with Healthy Mayonnaise",
    price: 240,
    currency: "EGP",
    nutrition: { calories: 316, protein: 23.5, carbs: 6.4, fat: 21.2 },
    tags: ["high-protein", "omega-3"],
  },
  {
    id: "deli-7",
    category: "deli",
    name: "Beef Brisket Wrap",
    description: "Served in Tortilla Bread, lettuce, tomatoes, topped with Healthy Mustard or Healthy Mayonnaise",
    price: 275,
    currency: "EGP",
    nutrition: { calories: 326, protein: 25.5, carbs: 5.1, fat: 26.2 },
    tags: ["high-protein", "low-carb"],
  },

  // ========== HOT SANDWICHES ==========
  {
    id: "hot-1",
    category: "hot",
    name: "Classic Beef Burger",
    description: "Pure local meat, Served with Lettuce, Sliced Tomatoes, topped with healthy Tasty burger sauce",
    price: 275,
    currency: "EGP",
    nutrition: { calories: 466, protein: 29.1, carbs: 6.9, fat: 38.7 },
    tags: ["high-protein", "low-carb"],
  },
  {
    id: "hot-2",
    category: "hot",
    name: "Beef Burger Cheese Mushroom",
    description: "Cooked with Fresh Mushrooms & melted cheese, Sliced Tomatoes, topped with healthy Tasty burger sauce",
    price: 325,
    currency: "EGP",
    nutrition: { calories: 567, protein: 39.9, carbs: 11.6, fat: 45.4 },
    tags: ["high-protein"],
  },
  {
    id: "hot-3",
    category: "hot",
    name: "Hot Dog",
    description: "Served with your choice of Healthy sauces; Mayonnaise, Mustard, BBQ on a bed of lettuce and tomato",
    price: 200,
    currency: "EGP",
    nutrition: { calories: 391, protein: 17.6, carbs: 7.9, fat: 33.2 },
    tags: ["low-carb"],
  },
  {
    id: "hot-4",
    category: "hot",
    name: "Oriental Sausage",
    description: "Served with roasted onions, green pepper & tomatoes",
    price: 250,
    currency: "EGP",
    nutrition: { calories: 513, protein: 20.5, carbs: 7.9, fat: 41.1 },
    tags: ["high-protein"],
  },

  // ========== VEGAN MENU ==========
  {
    id: "vegan-1",
    category: "vegan",
    name: "Vegan Hot Dog",
    description: "Served with your choice of Healthy sauces; Mayonnaise, Mustard, BBQ on a bed of lettuce and tomato",
    price: 215,
    currency: "EGP",
    nutrition: { calories: 313, protein: 20.5, carbs: 7.9, fat: 18 },
    tags: ["vegan", "vegetarian"],
  },
  {
    id: "vegan-2",
    category: "vegan",
    name: "Vegan Beef Burger",
    description: "Served with lettuce, sliced Tomatoes, topped with Vegan healthy Tasty burger sauce",
    price: 195,
    currency: "EGP",
    nutrition: { calories: 360, protein: 22.4, carbs: 19.72, fat: 25.98 },
    tags: ["vegan", "vegetarian"],
  },
  {
    id: "vegan-3",
    category: "vegan",
    name: "Vegan Chicken Burger",
    description: "Served with lettuce, Sliced Tomatoes, topped with Vegan healthy BBQ sauce",
    price: 195,
    currency: "EGP",
    nutrition: { calories: 346, protein: 21.5, carbs: 14.44, fat: 26.66 },
    tags: ["vegan", "vegetarian"],
  },
  {
    id: "vegan-4",
    category: "vegan",
    name: "Vegan Kofta",
    description: "Served with lettuce, Sliced Tomatoes, topped with Vegan healthy BBQ sauce",
    price: 200,
    currency: "EGP",
    nutrition: { calories: 347, protein: 22.15, carbs: 18.25, fat: 25.14 },
    tags: ["vegan", "vegetarian"],
  },
  {
    id: "vegan-5",
    category: "vegan",
    name: "Vegan Nuggets with Fries",
    description: "Air fried Nuggets (5 pcs), served with Air fried Potatoes, complemented with your choice of our healthy sauces",
    price: 225,
    currency: "EGP",
    nutrition: { calories: 441, protein: 13, carbs: 29.31, fat: 19.49 },
    tags: ["vegan", "vegetarian"],
  },

  // ========== SNACKS MENU ==========
  {
    id: "snacks-1",
    category: "snacks",
    name: "Keto Croissant Plain",
    description: "Gluten-free & Low-Carb keto croissant",
    price: 85,
    currency: "EGP",
    nutrition: { calories: 139, protein: 2.19, carbs: 1.2, fat: 14 },
    tags: ["vegan", "keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-2",
    category: "snacks",
    name: "Keto Cheese Croissant",
    description: "Gluten-free & Low-Carb keto croissant with cheese",
    price: 95,
    currency: "EGP",
    nutrition: { calories: 196, protein: 8.24, carbs: 1.42, fat: 15.1 },
    tags: ["keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-3",
    category: "snacks",
    name: "Keto Vegetables Pizza",
    description: "Gluten-free & Low-Carb keto pizza with vegetables",
    price: 250,
    currency: "EGP",
    nutrition: { calories: 225, protein: 10.5, carbs: 9.6, fat: 17.25 },
    tags: ["vegan", "keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-4",
    category: "snacks",
    name: "Keto Chicken Pizza",
    description: "Gluten-free & Low-Carb keto pizza with chicken",
    price: 280,
    currency: "EGP",
    nutrition: { calories: 150, protein: 7.5, carbs: 8, fat: 18 },
    tags: ["keto", "gluten-free", "low-carb", "high-protein"],
  },
  {
    id: "snacks-5",
    category: "snacks",
    name: "Keto Mini Pizza",
    description: "Gluten-free & Low-Carb keto mini pizza",
    price: 185,
    currency: "EGP",
    nutrition: { calories: 109, protein: 8, carbs: 4.5, fat: 7.9 },
    tags: ["vegan", "keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-6",
    category: "snacks",
    name: "Keto Mini Manakeesh Rumi",
    description: "Gluten-free & Low-Carb keto manakeesh with rumi cheese",
    price: 150,
    currency: "EGP",
    nutrition: { calories: 120, protein: 9.5, carbs: 2.5, fat: 4 },
    tags: ["keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-7",
    category: "snacks",
    name: "Keto Manakeesh Thyme",
    description: "Gluten-free & Low-Carb keto manakeesh with thyme",
    price: 105,
    currency: "EGP",
    nutrition: { calories: 102, protein: 7.5, carbs: 2.5, fat: 1.58 },
    tags: ["vegan", "keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-8",
    category: "snacks",
    name: "Keto Mini Manakeesh Vegan Cheese",
    description: "Gluten-free & Low-Carb keto manakeesh with vegan cheese",
    price: 180,
    currency: "EGP",
    nutrition: { calories: 140, protein: 3, carbs: 3.5, fat: 10.8 },
    tags: ["vegan", "keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-9",
    category: "snacks",
    name: "Keto Mini Manakeesh Spinach",
    description: "Gluten-free & Low-Carb keto manakeesh with spinach",
    price: 170,
    currency: "EGP",
    nutrition: { calories: 130, protein: 5.5, carbs: 2.7, fat: 8.58 },
    tags: ["vegan", "keto", "gluten-free", "low-carb"],
  },
  {
    id: "snacks-10",
    category: "snacks",
    name: "Keto Manakeesh Pastrami",
    description: "Gluten-free & Low-Carb keto manakeesh with pastrami",
    price: 180,
    currency: "EGP",
    nutrition: { calories: 139, protein: 13.5, carbs: 3.5, fat: 6.5 },
    tags: ["keto", "gluten-free", "low-carb", "high-protein"],
  },
  {
    id: "snacks-11",
    category: "snacks",
    name: "Healthy Nachos",
    description: "Natural 100% healthy nachos",
    price: 85,
    currency: "EGP",
    nutrition: { calories: 219, protein: 9, carbs: 0.76, fat: 10 },
    tags: ["vegan", "low-carb"],
  },
  {
    id: "snacks-12",
    category: "snacks",
    name: "Healthy Pop Corn",
    description: "Natural 100% healthy air-popped popcorn",
    price: 50,
    currency: "EGP",
    nutrition: { calories: 55, protein: 1, carbs: 4.8, fat: 2.7 },
    tags: ["vegan", "low-carb"],
  },

  // ========== DESSERTS ==========
  {
    id: "desserts-1",
    category: "desserts",
    name: "Cheese Cake Keto/Vegan",
    description: "Gluten-free & Low-carb keto or vegan cheesecake",
    price: 155,
    currency: "EGP",
    nutrition: { calories: 220, protein: 4.75, carbs: 2, fat: 8.25 },
    tags: ["keto", "low-carb", "sugar-free"],
  },
  {
    id: "desserts-2",
    category: "desserts",
    name: "Chocolate Fudge - Mousse",
    description: "Rich chocolate fudge mousse",
    price: 150,
    currency: "EGP",
    nutrition: { calories: 390, protein: 6.5, carbs: 4.25, fat: 19.25 },
    tags: ["sugar-free"],
  },
  {
    id: "desserts-3",
    category: "desserts",
    name: "Oreo Cake",
    description: "Gluten-free & Low-carb Oreo cake",
    price: 150,
    currency: "EGP",
    nutrition: { calories: 150, protein: 2.9, carbs: 3.67, fat: 11.69 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-4",
    category: "desserts",
    name: "Red Velvet",
    description: "Gluten-free & Low-carb red velvet cake",
    price: 150,
    currency: "EGP",
    nutrition: { calories: 150, protein: 2.9, carbs: 3.67, fat: 11.69 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-5",
    category: "desserts",
    name: "Carrot Cake (Caramel/Cream)",
    description: "Gluten-free & Low-carb carrot cake with caramel or cream",
    price: 150,
    currency: "EGP",
    nutrition: { calories: 160, protein: 8, carbs: 3.8, fat: 12 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-6",
    category: "desserts",
    name: "Tiramisu",
    description: "Gluten-free & Low-carb tiramisu",
    price: 150,
    currency: "EGP",
    nutrition: { calories: 150, protein: 2.5, carbs: 6.7, fat: 11.69 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-7",
    category: "desserts",
    name: "Honey Cake",
    description: "Gluten-free & Low-carb honey cake",
    price: 155,
    currency: "EGP",
    nutrition: { calories: 170, protein: 0.7, carbs: 4.25, fat: 13.25 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-8",
    category: "desserts",
    name: "Chocolate Molten Cake",
    description: "Warm chocolate molten cake with flowing center",
    price: 185,
    currency: "EGP",
    nutrition: { calories: 300, protein: 9.75, carbs: 2.5, fat: 19.65 },
    tags: ["sugar-free"],
  },
  {
    id: "desserts-9",
    category: "desserts",
    name: "Volcano Cake Caramel/Chocoberry",
    description: "Gluten-free & Low-carb volcano cake with caramel or chocoberry",
    price: 155,
    currency: "EGP",
    nutrition: { calories: 188, protein: 6, carbs: 5, fat: 11 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-10",
    category: "desserts",
    name: "Chocolate Tart",
    description: "Gluten-free & Low-carb chocolate tart",
    price: 150,
    currency: "EGP",
    nutrition: { calories: 125, protein: 3.5, carbs: 6.5, fat: 8.5 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-11",
    category: "desserts",
    name: "Apple Tart",
    description: "Gluten-free & Low-carb apple tart",
    price: 140,
    currency: "EGP",
    nutrition: { calories: 110, protein: 3, carbs: 3, fat: 8.5 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-12",
    category: "desserts",
    name: "Walnut & Caramel Tart",
    description: "Gluten-free & Low-carb walnut and caramel tart",
    price: 160,
    currency: "EGP",
    nutrition: { calories: 140, protein: 4.5, carbs: 7.5, fat: 10.25 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-13",
    category: "desserts",
    name: "Cinnamon Roll",
    description: "Gluten-free & Low-carb cinnamon roll",
    price: 120,
    currency: "EGP",
    nutrition: { calories: 248, protein: 6.5, carbs: 15.5, fat: 12.5 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-14",
    category: "desserts",
    name: "Brownies",
    description: "Gluten-free & Low-carb brownies",
    price: 100,
    currency: "EGP",
    nutrition: { calories: 126, protein: 3.5, carbs: 8, fat: 8 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-15",
    category: "desserts",
    name: "Eclair (Chocolate/Caramel)",
    description: "Gluten-free & Low-carb eclair with chocolate or caramel",
    price: 110,
    currency: "EGP",
    nutrition: { calories: 145, protein: 1, carbs: 3.27, fat: 5.94 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-16",
    category: "desserts",
    name: "Donuts",
    description: "Gluten-free & Low-carb donuts",
    price: 105,
    currency: "EGP",
    nutrition: { calories: 88, protein: 4.25, carbs: 2.13, fat: 0.81 },
    tags: ["keto", "low-carb"],
  },
  {
    id: "desserts-17",
    category: "desserts",
    name: "Lotus Biscoff Cup",
    description: "Lotus biscuit with cream filling",
    price: 180,
    currency: "EGP",
    nutrition: { calories: 360, protein: 8, carbs: 24, fat: 15 },
    tags: [],
  },
  {
    id: "desserts-18",
    category: "desserts",
    name: "Profitrol",
    description: "Cream-filled profiteroles with chocolate coating",
    price: 180,
    currency: "EGP",
    nutrition: { calories: 270, protein: 6.69, carbs: 9.08, fat: 15.9 },
    tags: [],
  },

  // ========== COFFEE & DRINKS ==========
  // HOT COFFEE
  {
    id: "coffee-1",
    category: "coffee",
    name: "Espresso",
    price: 60,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  {
    id: "coffee-2",
    category: "coffee",
    name: "Americano",
    price: 90,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  {
    id: "coffee-3",
    category: "coffee",
    name: "Cappuccino",
    price: 100,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-4",
    category: "coffee",
    name: "Latte",
    price: 140,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-5",
    category: "coffee",
    name: "Cortado",
    price: 120,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-6",
    category: "coffee",
    name: "Flat White",
    price: 150,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-7",
    category: "coffee",
    name: "Mocha",
    price: 180,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-8",
    category: "coffee",
    name: "Macchiato",
    price: 70,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-9",
    category: "coffee",
    name: "Caramel Macchiato",
    price: 140,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-10",
    category: "coffee",
    name: "Turkish Coffee",
    price: 50,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  {
    id: "coffee-11",
    category: "coffee",
    name: "French Coffee",
    price: 60,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  {
    id: "coffee-12",
    category: "coffee",
    name: "Hazelnut Coffee",
    price: 75,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-13",
    category: "coffee",
    name: "Nutella Coffee",
    price: 85,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-14",
    category: "coffee",
    name: "Spanish Latte",
    price: 180,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-15",
    category: "coffee",
    name: "Filter Coffee",
    price: 150,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  // MATCHA
  {
    id: "coffee-16",
    category: "coffee",
    name: "Matcha Tea",
    price: 60,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-17",
    category: "coffee",
    name: "Matcha Latte",
    price: 100,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-18",
    category: "coffee",
    name: "Matcha Honey Latte",
    price: 120,
    currency: "EGP",
    tags: [],
  },
  // HOT DRINKS
  {
    id: "coffee-19",
    category: "coffee",
    name: "Hot Chocolate",
    price: 100,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-20",
    category: "coffee",
    name: "Apple Cider",
    price: 80,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-21",
    category: "coffee",
    name: "Detox Tea",
    price: 75,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-22",
    category: "coffee",
    name: "Herbal Tea",
    price: 60,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-23",
    category: "coffee",
    name: "Black/Green Tea",
    price: 45,
    currency: "EGP",
    tags: ["sugar-free", "vegan"],
  },
  // ICED COFFEE
  {
    id: "coffee-24",
    category: "coffee",
    name: "Iced Americano",
    price: 95,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  {
    id: "coffee-25",
    category: "coffee",
    name: "Iced Orange Americano",
    price: 120,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-26",
    category: "coffee",
    name: "Cappuccino Freddo",
    price: 105,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-27",
    category: "coffee",
    name: "Espresso Freddo",
    price: 85,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  {
    id: "coffee-28",
    category: "coffee",
    name: "Iced Filter Coffee",
    price: 155,
    currency: "EGP",
    tags: ["sugar-free"],
  },
  {
    id: "coffee-29",
    category: "coffee",
    name: "Iced Caramel Macchiato",
    price: 150,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-30",
    category: "coffee",
    name: "Iced Mocha",
    price: 190,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-31",
    category: "coffee",
    name: "Iced Latte",
    price: 145,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-32",
    category: "coffee",
    name: "Iced Matcha Latte",
    price: 110,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-33",
    category: "coffee",
    name: "Frappuccino",
    price: 150,
    currency: "EGP",
    tags: [],
  },
  {
    id: "coffee-34",
    category: "coffee",
    name: "Milkshake",
    price: 130,
    currency: "EGP",
    tags: [],
  },
  // FRESH JUICES & SMOOTHIES
  {
    id: "coffee-35",
    category: "coffee",
    name: "Avocado",
    price: 180,
    currency: "EGP",
    tags: ["vegan", "high-protein"],
  },
  {
    id: "coffee-36",
    category: "coffee",
    name: "Kiwi",
    price: 130,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-37",
    category: "coffee",
    name: "Strawberry",
    price: 90,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-38",
    category: "coffee",
    name: "Strawberry Lemonade",
    price: 120,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-39",
    category: "coffee",
    name: "Guava",
    price: 90,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-40",
    category: "coffee",
    name: "Lemon",
    price: 65,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-41",
    category: "coffee",
    name: "Lemon Mint",
    price: 75,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-42",
    category: "coffee",
    name: "Orange",
    price: 65,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-43",
    category: "coffee",
    name: "Mango",
    price: 100,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-44",
    category: "coffee",
    name: "Fresh Mix Juice",
    price: 180,
    currency: "EGP",
    tags: ["vegan"],
  },
  // SOFT DRINKS
  {
    id: "coffee-45",
    category: "coffee",
    name: "Green Cola",
    price: 50,
    currency: "EGP",
    tags: ["vegan", "sugar-free"],
  },
  {
    id: "coffee-46",
    category: "coffee",
    name: "V Cola",
    price: 35,
    currency: "EGP",
    tags: ["vegan"],
  },
  {
    id: "coffee-47",
    category: "coffee",
    name: "Lakanto Cola",
    price: 50,
    currency: "EGP",
    tags: ["vegan", "sugar-free"],
  },
  {
    id: "coffee-48",
    category: "coffee",
    name: "Club Soda",
    price: 50,
    currency: "EGP",
    tags: ["vegan", "sugar-free"],
  },
  {
    id: "coffee-49",
    category: "coffee",
    name: "FLO Water",
    price: 30,
    currency: "EGP",
    tags: ["vegan", "sugar-free"],
  },
  {
    id: "coffee-50",
    category: "coffee",
    name: "Water",
    price: 20,
    currency: "EGP",
    tags: ["vegan", "sugar-free"],
  },
];

export function getItemsByCategory(category: MenuItem["category"]): MenuItem[] {
  return menuItems.filter((item) => item.category === category);
}

export function searchMenuItems(query: string): MenuItem[] {
  const q = query.toLowerCase();
  return menuItems.filter(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      item.description?.toLowerCase().includes(q) ||
      item.tags?.some((tag) => tag.toLowerCase().includes(q))
  );
}
